// GENERATED by scripts/generate-app-data.ts — do not edit by hand.
// Source of truth: supabase/seed/taxonomy_master_from_sure.csv + vendor_to_category_starter.yaml

export interface SeedCategory { name: string; parent: string | null; color: string; icon: string; autoAssignable: boolean; }
export interface SeedRule { priority: number; match: string; category: string; }
export interface SeedAccount { name: string; institution: string; kind: string; }

export const SEED_CATEGORIES: SeedCategory[] = [
  {
    "name": "Digital Gold Purchase",
    "parent": "08 Invest-it",
    "color": "#0f766e",
    "icon": "coins",
    "autoAssignable": true
  },
  {
    "name": "Unplanned Social Spend",
    "parent": "14 Cash Leakage Watchlist",
    "color": "#ef4444",
    "icon": "users",
    "autoAssignable": false
  },
  {
    "name": "Business Loan EMI",
    "parent": "05 Debt & Credit",
    "color": "#7c3aed",
    "icon": "briefcase",
    "autoAssignable": true
  },
  {
    "name": "Home Repairs Planned",
    "parent": "06 Planned Needs",
    "color": "#0891b2",
    "icon": "hammer",
    "autoAssignable": true
  },
  {
    "name": "Fitness Classes",
    "parent": "03 Spend-it Wants",
    "color": "#f97316",
    "icon": "dumbbell",
    "autoAssignable": true
  },
  {
    "name": "Income Tax Payment",
    "parent": "12 Taxes & Compliance",
    "color": "#ca8a04",
    "icon": "landmark",
    "autoAssignable": true
  },
  {
    "name": "Portfolio Rebalance",
    "parent": "08 Invest-it",
    "color": "#0f766e",
    "icon": "shuffle",
    "autoAssignable": true
  },
  {
    "name": "Emergency Fund Contribution",
    "parent": "04 Protect",
    "color": "#dc2626",
    "icon": "shield",
    "autoAssignable": true
  },
  {
    "name": "Fitness Gear",
    "parent": "07 Planned Wants",
    "color": "#ec4899",
    "icon": "dumbbell",
    "autoAssignable": true
  },
  {
    "name": "Personal Development Course Optional",
    "parent": "07 Planned Wants",
    "color": "#ec4899",
    "icon": "book-open",
    "autoAssignable": true
  },
  {
    "name": "Needs Review",
    "parent": "15 Review Buckets",
    "color": "#334155",
    "icon": "clipboard-check",
    "autoAssignable": false
  },
  {
    "name": "Business Assets",
    "parent": "09 Assets & Net Worth",
    "color": "#475569",
    "icon": "briefcase-business",
    "autoAssignable": true
  },
  {
    "name": "Borrowed Money Received",
    "parent": "05 Debt & Credit",
    "color": "#7c3aed",
    "icon": "hand-coins",
    "autoAssignable": true
  },
  {
    "name": "Recurring Deposit",
    "parent": "08 Invest-it",
    "color": "#0f766e",
    "icon": "calendar-days",
    "autoAssignable": true
  },
  {
    "name": "Business Equipment Essential",
    "parent": "06 Planned Needs",
    "color": "#0891b2",
    "icon": "briefcase",
    "autoAssignable": true
  },
  {
    "name": "Debt Fund Investment",
    "parent": "08 Invest-it",
    "color": "#0f766e",
    "icon": "landmark",
    "autoAssignable": true
  },
  {
    "name": "Job Loss Buffer",
    "parent": "04 Protect",
    "color": "#dc2626",
    "icon": "briefcase",
    "autoAssignable": true
  },
  {
    "name": "Religious / Community Giving",
    "parent": "13 Family & Giving",
    "color": "#be123c",
    "icon": "flower-2",
    "autoAssignable": true
  },
  {
    "name": "Gifting Fund Optional",
    "parent": "07 Planned Wants",
    "color": "#ec4899",
    "icon": "gift",
    "autoAssignable": true
  },
  {
    "name": "Income Protection Buffer",
    "parent": "04 Protect",
    "color": "#dc2626",
    "icon": "shield-check",
    "autoAssignable": true
  },
  {
    "name": "Document Renewal Reserve",
    "parent": "04 Protect",
    "color": "#dc2626",
    "icon": "file-check",
    "autoAssignable": true
  },
  {
    "name": "Gas",
    "parent": "02 Spend-it Needs",
    "color": "#2563eb",
    "icon": "flame",
    "autoAssignable": true
  },
  {
    "name": "Zerodha Coin Mutual Funds",
    "parent": "09 Assets & Net Worth",
    "color": "#475569",
    "icon": "pie-chart",
    "autoAssignable": true
  },
  {
    "name": "Website Tools",
    "parent": "11 Work & Business",
    "color": "#9333ea",
    "icon": "layout-template",
    "autoAssignable": true
  },
  {
    "name": "Wallet Withdrawal",
    "parent": "10 Transfers & Adjustments",
    "color": "#64748b",
    "icon": "wallet",
    "autoAssignable": true
  },
  {
    "name": "Anniversary / Birthday Plan",
    "parent": "07 Planned Wants",
    "color": "#ec4899",
    "icon": "cake",
    "autoAssignable": true
  },
  {
    "name": "Packaging Samples",
    "parent": "11 Work & Business",
    "color": "#9333ea",
    "icon": "package",
    "autoAssignable": true
  },
  {
    "name": "Dividend Reinvestment",
    "parent": "08 Invest-it",
    "color": "#0f766e",
    "icon": "refresh-cw",
    "autoAssignable": true
  },
  {
    "name": "Emergency Fund Review",
    "parent": "15 Review Buckets",
    "color": "#334155",
    "icon": "shield-check",
    "autoAssignable": false
  },
  {
    "name": "Education / Course Essential",
    "parent": "06 Planned Needs",
    "color": "#0891b2",
    "icon": "graduation-cap",
    "autoAssignable": true
  },
  {
    "name": "Games",
    "parent": "03 Spend-it Wants",
    "color": "#f97316",
    "icon": "gamepad-2",
    "autoAssignable": true
  },
  {
    "name": "Goal Investment",
    "parent": "08 Invest-it",
    "color": "#0f766e",
    "icon": "target",
    "autoAssignable": true
  },
  {
    "name": "Annual Insurance Reserve",
    "parent": "04 Protect",
    "color": "#dc2626",
    "icon": "calendar-clock",
    "autoAssignable": true
  },
  {
    "name": "Parents Support Essential",
    "parent": "02 Spend-it Needs",
    "color": "#2563eb",
    "icon": "heart",
    "autoAssignable": true
  },
  {
    "name": "Goal Funding Review",
    "parent": "15 Review Buckets",
    "color": "#334155",
    "icon": "target",
    "autoAssignable": false
  },
  {
    "name": "Courier / Shipping Business",
    "parent": "11 Work & Business",
    "color": "#9333ea",
    "icon": "truck",
    "autoAssignable": true
  },
  {
    "name": "Reversal",
    "parent": "10 Transfers & Adjustments",
    "color": "#64748b",
    "icon": "rotate-ccw",
    "autoAssignable": true
  },
  {
    "name": "Movies / Events",
    "parent": "03 Spend-it Wants",
    "color": "#f97316",
    "icon": "ticket",
    "autoAssignable": true
  },
  {
    "name": "Home Loan EMI",
    "parent": "05 Debt & Credit",
    "color": "#7c3aed",
    "icon": "home",
    "autoAssignable": true
  },
  {
    "name": "Rent Deposit / Moving Cost",
    "parent": "06 Planned Needs",
    "color": "#0891b2",
    "icon": "home",
    "autoAssignable": true
  },
  {
    "name": "Printing / Proofing",
    "parent": "11 Work & Business",
    "color": "#9333ea",
    "icon": "printer",
    "autoAssignable": true
  },
  {
    "name": "Investment Funding Transfer",
    "parent": "10 Transfers & Adjustments",
    "color": "#64748b",
    "icon": "trending-up",
    "autoAssignable": true
  },
  {
    "name": "Invest-it to Income Transfer",
    "parent": "10 Transfers & Adjustments",
    "color": "#64748b",
    "icon": "arrow-left-right",
    "autoAssignable": true
  },
  {
    "name": "Cash Withdrawal",
    "parent": "10 Transfers & Adjustments",
    "color": "#64748b",
    "icon": "banknote",
    "autoAssignable": true
  },
  {
    "name": "Money Returned To Others",
    "parent": "05 Debt & Credit",
    "color": "#7c3aed",
    "icon": "rotate-ccw",
    "autoAssignable": true
  },
  {
    "name": "08 Invest-it",
    "parent": null,
    "color": "#0f766e",
    "icon": "trending-up",
    "autoAssignable": true
  },
  {
    "name": "Domestic Help",
    "parent": "02 Spend-it Needs",
    "color": "#2563eb",
    "icon": "handshake",
    "autoAssignable": true
  },
  {
    "name": "Beauty / Grooming",
    "parent": "03 Spend-it Wants",
    "color": "#f97316",
    "icon": "scissors",
    "autoAssignable": true
  },
  {
    "name": "Client Hospitality",
    "parent": "11 Work & Business",
    "color": "#9333ea",
    "icon": "coffee",
    "autoAssignable": true
  },
  {
    "name": "Lumpsum Mutual Fund",
    "parent": "08 Invest-it",
    "color": "#0f766e",
    "icon": "bar-chart-3",
    "autoAssignable": true
  },
  {
    "name": "Credit Card Late Fee",
    "parent": "05 Debt & Credit",
    "color": "#7c3aed",
    "icon": "alert-triangle",
    "autoAssignable": true
  },
  {
    "name": "Advance Tax",
    "parent": "12 Taxes & Compliance",
    "color": "#ca8a04",
    "icon": "calendar-clock",
    "autoAssignable": true
  },
  {
    "name": "Wallet Load",
    "parent": "10 Transfers & Adjustments",
    "color": "#64748b",
    "icon": "wallet-cards",
    "autoAssignable": true
  },
  {
    "name": "Design Project Income",
    "parent": "01 Income",
    "color": "#16a34a",
    "icon": "palette",
    "autoAssignable": true
  },
  {
    "name": "Zerodha Kite Holdings",
    "parent": "09 Assets & Net Worth",
    "color": "#475569",
    "icon": "candlestick-chart",
    "autoAssignable": true
  },
  {
    "name": "Child Education Reserve",
    "parent": "06 Planned Needs",
    "color": "#0891b2",
    "icon": "school",
    "autoAssignable": true
  },
  {
    "name": "Professional Tax",
    "parent": "12 Taxes & Compliance",
    "color": "#ca8a04",
    "icon": "badge-indian-rupee",
    "autoAssignable": true
  },
  {
    "name": "Duplicate Review",
    "parent": "15 Review Buckets",
    "color": "#334155",
    "icon": "copy-check",
    "autoAssignable": false
  },
  {
    "name": "Loan Processing Fee",
    "parent": "05 Debt & Credit",
    "color": "#7c3aed",
    "icon": "file-text",
    "autoAssignable": true
  },
  {
    "name": "Tax Refund Received",
    "parent": "12 Taxes & Compliance",
    "color": "#ca8a04",
    "icon": "undo-2",
    "autoAssignable": true
  },
  {
    "name": "Laundry & Cleaning",
    "parent": "02 Spend-it Needs",
    "color": "#2563eb",
    "icon": "shirt",
    "autoAssignable": true
  },
  {
    "name": "Internet / WiFi",
    "parent": "02 Spend-it Needs",
    "color": "#2563eb",
    "icon": "wifi",
    "autoAssignable": true
  },
  {
    "name": "Consulting Income",
    "parent": "01 Income",
    "color": "#16a34a",
    "icon": "presentation",
    "autoAssignable": true
  },
  {
    "name": "Food Delivery Leakage",
    "parent": "14 Cash Leakage Watchlist",
    "color": "#ef4444",
    "icon": "bike",
    "autoAssignable": false
  },
  {
    "name": "Cash Balance Snapshot",
    "parent": "09 Assets & Net Worth",
    "color": "#475569",
    "icon": "wallet",
    "autoAssignable": true
  },
  {
    "name": "Duplicate / Ignore",
    "parent": "10 Transfers & Adjustments",
    "color": "#64748b",
    "icon": "ban",
    "autoAssignable": true
  },
  {
    "name": "Eating Out",
    "parent": "03 Spend-it Wants",
    "color": "#f97316",
    "icon": "utensils",
    "autoAssignable": true
  },
  {
    "name": "Income to Invest-it Transfer",
    "parent": "10 Transfers & Adjustments",
    "color": "#64748b",
    "icon": "arrow-right-left",
    "autoAssignable": true
  },
  {
    "name": "Client Meeting Travel",
    "parent": "11 Work & Business",
    "color": "#9333ea",
    "icon": "car",
    "autoAssignable": true
  },
  {
    "name": "Pet Care Essentials",
    "parent": "02 Spend-it Needs",
    "color": "#2563eb",
    "icon": "paw-print",
    "autoAssignable": true
  },
  {
    "name": "Appliance Replacement Essential",
    "parent": "06 Planned Needs",
    "color": "#0891b2",
    "icon": "plug",
    "autoAssignable": true
  },
  {
    "name": "Wants Review",
    "parent": "15 Review Buckets",
    "color": "#334155",
    "icon": "clipboard-list",
    "autoAssignable": false
  },
  {
    "name": "Portfolio / Case Study Expense",
    "parent": "11 Work & Business",
    "color": "#9333ea",
    "icon": "presentation",
    "autoAssignable": true
  },
  {
    "name": "Annual Tax Payment",
    "parent": "06 Planned Needs",
    "color": "#0891b2",
    "icon": "landmark",
    "autoAssignable": true
  },
  {
    "name": "Design Software",
    "parent": "11 Work & Business",
    "color": "#9333ea",
    "icon": "monitor-cog",
    "autoAssignable": true
  },
  {
    "name": "Late Fees Leakage",
    "parent": "14 Cash Leakage Watchlist",
    "color": "#ef4444",
    "icon": "alert-triangle",
    "autoAssignable": false
  },
  {
    "name": "Net Worth Adjustment",
    "parent": "09 Assets & Net Worth",
    "color": "#475569",
    "icon": "sliders-horizontal",
    "autoAssignable": true
  },
  {
    "name": "Household Supplies",
    "parent": "02 Spend-it Needs",
    "color": "#2563eb",
    "icon": "shopping-cart",
    "autoAssignable": true
  },
  {
    "name": "Equity Sale",
    "parent": "08 Invest-it",
    "color": "#0f766e",
    "icon": "line-chart",
    "autoAssignable": true
  },
  {
    "name": "Education Loan EMI",
    "parent": "05 Debt & Credit",
    "color": "#7c3aed",
    "icon": "graduation-cap",
    "autoAssignable": true
  },
  {
    "name": "Lifestyle Upgrade",
    "parent": "03 Spend-it Wants",
    "color": "#f97316",
    "icon": "gem",
    "autoAssignable": true
  },
  {
    "name": "Contingency Buffer",
    "parent": "04 Protect",
    "color": "#dc2626",
    "icon": "life-buoy",
    "autoAssignable": true
  },
  {
    "name": "Society Maintenance",
    "parent": "02 Spend-it Needs",
    "color": "#2563eb",
    "icon": "building",
    "autoAssignable": true
  },
  {
    "name": "BNPL Payment",
    "parent": "05 Debt & Credit",
    "color": "#7c3aed",
    "icon": "calendar",
    "autoAssignable": true
  },
  {
    "name": "Basic Personal Care",
    "parent": "02 Spend-it Needs",
    "color": "#2563eb",
    "icon": "bath",
    "autoAssignable": true
  },
  {
    "name": "Travel Local Leisure",
    "parent": "03 Spend-it Wants",
    "color": "#f97316",
    "icon": "map",
    "autoAssignable": true
  },
  {
    "name": "Tax Review",
    "parent": "15 Review Buckets",
    "color": "#334155",
    "icon": "file-text",
    "autoAssignable": false
  },
  {
    "name": "Gadgets Non-essential",
    "parent": "03 Spend-it Wants",
    "color": "#f97316",
    "icon": "smartphone",
    "autoAssignable": true
  },
  {
    "name": "ETF Purchase",
    "parent": "08 Invest-it",
    "color": "#0f766e",
    "icon": "layers",
    "autoAssignable": true
  },
  {
    "name": "Invest-it Transfer",
    "parent": "08 Invest-it",
    "color": "#0f766e",
    "icon": "repeat",
    "autoAssignable": true
  },
  {
    "name": "Rent Received",
    "parent": "01 Income",
    "color": "#16a34a",
    "icon": "home",
    "autoAssignable": true
  },
  {
    "name": "Furniture Upgrade",
    "parent": "07 Planned Wants",
    "color": "#ec4899",
    "icon": "armchair",
    "autoAssignable": true
  },
  {
    "name": "Children Essentials",
    "parent": "02 Spend-it Needs",
    "color": "#2563eb",
    "icon": "baby",
    "autoAssignable": true
  },
  {
    "name": "Professional Software Renewal",
    "parent": "06 Planned Needs",
    "color": "#0891b2",
    "icon": "monitor-cog",
    "autoAssignable": true
  },
  {
    "name": "Professional Learning",
    "parent": "11 Work & Business",
    "color": "#9333ea",
    "icon": "graduation-cap",
    "autoAssignable": true
  },
  {
    "name": "Subscription Creep",
    "parent": "14 Cash Leakage Watchlist",
    "color": "#ef4444",
    "icon": "repeat",
    "autoAssignable": false
  },
  {
    "name": "Emergency Fund Withdrawal",
    "parent": "04 Protect",
    "color": "#dc2626",
    "icon": "shield-alert",
    "autoAssignable": true
  },
  {
    "name": "Brokerage Charges",
    "parent": "08 Invest-it",
    "color": "#0f766e",
    "icon": "receipt",
    "autoAssignable": true
  },
  {
    "name": "Home Decor",
    "parent": "03 Spend-it Wants",
    "color": "#f97316",
    "icon": "sofa",
    "autoAssignable": true
  },
  {
    "name": "Parents Support",
    "parent": "13 Family & Giving",
    "color": "#be123c",
    "icon": "heart",
    "autoAssignable": true
  },
  {
    "name": "Festival / Celebration Fund",
    "parent": "07 Planned Wants",
    "color": "#ec4899",
    "icon": "party-popper",
    "autoAssignable": true
  },
  {
    "name": "Business Phone / Internet",
    "parent": "11 Work & Business",
    "color": "#9333ea",
    "icon": "wifi",
    "autoAssignable": true
  },
  {
    "name": "Balance Correction",
    "parent": "10 Transfers & Adjustments",
    "color": "#64748b",
    "icon": "sliders-horizontal",
    "autoAssignable": true
  },
  {
    "name": "Personal Loan EMI",
    "parent": "05 Debt & Credit",
    "color": "#7c3aed",
    "icon": "banknote",
    "autoAssignable": true
  },
  {
    "name": "Tax Filing Reserve",
    "parent": "06 Planned Needs",
    "color": "#0891b2",
    "icon": "file-check",
    "autoAssignable": true
  },
  {
    "name": "Parents Medical Reserve",
    "parent": "06 Planned Needs",
    "color": "#0891b2",
    "icon": "heart-pulse",
    "autoAssignable": true
  },
  {
    "name": "Home Insurance Premium",
    "parent": "04 Protect",
    "color": "#dc2626",
    "icon": "home",
    "autoAssignable": true
  },
  {
    "name": "Loan Repayment Received",
    "parent": "01 Income",
    "color": "#16a34a",
    "icon": "hand-coins",
    "autoAssignable": true
  },
  {
    "name": "Equipment for Studio",
    "parent": "11 Work & Business",
    "color": "#9333ea",
    "icon": "laptop",
    "autoAssignable": true
  },
  {
    "name": "Rent / Housing",
    "parent": "02 Spend-it Needs",
    "color": "#2563eb",
    "icon": "house",
    "autoAssignable": true
  },
  {
    "name": "09 Assets & Net Worth",
    "parent": null,
    "color": "#475569",
    "icon": "landmark",
    "autoAssignable": true
  },
  {
    "name": "Mobile Phone",
    "parent": "02 Spend-it Needs",
    "color": "#2563eb",
    "icon": "smartphone",
    "autoAssignable": true
  },
  {
    "name": "11 Work & Business",
    "parent": null,
    "color": "#9333ea",
    "icon": "briefcase-business",
    "autoAssignable": true
  },
  {
    "name": "15 Review Buckets",
    "parent": null,
    "color": "#334155",
    "icon": "clipboard-check",
    "autoAssignable": false
  },
  {
    "name": "Sovereign Gold Bond",
    "parent": "08 Invest-it",
    "color": "#0f766e",
    "icon": "medal",
    "autoAssignable": true
  },
  {
    "name": "Family Gifts",
    "parent": "13 Family & Giving",
    "color": "#be123c",
    "icon": "gift",
    "autoAssignable": true
  },
  {
    "name": "Festival Splurge",
    "parent": "03 Spend-it Wants",
    "color": "#f97316",
    "icon": "sparkles",
    "autoAssignable": true
  },
  {
    "name": "Refunds Received",
    "parent": "01 Income",
    "color": "#16a34a",
    "icon": "undo-2",
    "autoAssignable": true
  },
  {
    "name": "07 Planned Wants",
    "parent": null,
    "color": "#ec4899",
    "icon": "calendar-heart",
    "autoAssignable": true
  },
  {
    "name": "Money Lent To Others",
    "parent": "05 Debt & Credit",
    "color": "#7c3aed",
    "icon": "handshake",
    "autoAssignable": true
  },
  {
    "name": "Wedding / Family Event",
    "parent": "13 Family & Giving",
    "color": "#be123c",
    "icon": "party-popper",
    "autoAssignable": true
  },
  {
    "name": "13 Family & Giving",
    "parent": null,
    "color": "#be123c",
    "icon": "heart-handshake",
    "autoAssignable": true
  },
  {
    "name": "Weekend Trips",
    "parent": "03 Spend-it Wants",
    "color": "#f97316",
    "icon": "backpack",
    "autoAssignable": true
  },
  {
    "name": "Coffee / Cafes",
    "parent": "03 Spend-it Wants",
    "color": "#f97316",
    "icon": "coffee",
    "autoAssignable": true
  },
  {
    "name": "Vehicle Service Planned",
    "parent": "06 Planned Needs",
    "color": "#0891b2",
    "icon": "car",
    "autoAssignable": true
  },
  {
    "name": "Impulse Purchases",
    "parent": "03 Spend-it Wants",
    "color": "#f97316",
    "icon": "zap",
    "autoAssignable": true
  },
  {
    "name": "Laptop Replacement for Work",
    "parent": "06 Planned Needs",
    "color": "#0891b2",
    "icon": "laptop",
    "autoAssignable": true
  },
  {
    "name": "CAS / Demat Holdings",
    "parent": "09 Assets & Net Worth",
    "color": "#475569",
    "icon": "files",
    "autoAssignable": true
  },
  {
    "name": "Own Account Transfer",
    "parent": "10 Transfers & Adjustments",
    "color": "#64748b",
    "icon": "repeat",
    "autoAssignable": true
  },
  {
    "name": "Interest Income",
    "parent": "01 Income",
    "color": "#16a34a",
    "icon": "percent",
    "autoAssignable": true
  },
  {
    "name": "03 Spend-it Wants",
    "parent": null,
    "color": "#f97316",
    "icon": "sparkles",
    "autoAssignable": true
  },
  {
    "name": "ATM / Bank Fees Leakage",
    "parent": "14 Cash Leakage Watchlist",
    "color": "#ef4444",
    "icon": "landmark",
    "autoAssignable": false
  },
  {
    "name": "Essential Subscriptions",
    "parent": "02 Spend-it Needs",
    "color": "#2563eb",
    "icon": "badge-check",
    "autoAssignable": true
  },
  {
    "name": "Apps & Digital Subscriptions",
    "parent": "03 Spend-it Wants",
    "color": "#f97316",
    "icon": "app-window",
    "autoAssignable": true
  },
  {
    "name": "Legal / Accounting",
    "parent": "11 Work & Business",
    "color": "#9333ea",
    "icon": "scale",
    "autoAssignable": true
  },
  {
    "name": "Groceries",
    "parent": "02 Spend-it Needs",
    "color": "#2563eb",
    "icon": "shopping-basket",
    "autoAssignable": true
  },
  {
    "name": "01 Income",
    "parent": null,
    "color": "#16a34a",
    "icon": "wallet",
    "autoAssignable": true
  },
  {
    "name": "Loan To Family / Friend",
    "parent": "13 Family & Giving",
    "color": "#be123c",
    "icon": "handshake",
    "autoAssignable": true
  },
  {
    "name": "Vacation Spend",
    "parent": "03 Spend-it Wants",
    "color": "#f97316",
    "icon": "plane",
    "autoAssignable": true
  },
  {
    "name": "Medical Procedure Planned",
    "parent": "06 Planned Needs",
    "color": "#0891b2",
    "icon": "hospital",
    "autoAssignable": true
  },
  {
    "name": "Vehicle Insurance Premium",
    "parent": "04 Protect",
    "color": "#dc2626",
    "icon": "car",
    "autoAssignable": true
  },
  {
    "name": "Fonts / Assets",
    "parent": "11 Work & Business",
    "color": "#9333ea",
    "icon": "type",
    "autoAssignable": true
  },
  {
    "name": "Food Delivery",
    "parent": "03 Spend-it Wants",
    "color": "#f97316",
    "icon": "bike",
    "autoAssignable": true
  },
  {
    "name": "Real Estate Value",
    "parent": "09 Assets & Net Worth",
    "color": "#475569",
    "icon": "home",
    "autoAssignable": true
  },
  {
    "name": "Business Income",
    "parent": "01 Income",
    "color": "#16a34a",
    "icon": "building-2",
    "autoAssignable": true
  },
  {
    "name": "E-commerce Leakage",
    "parent": "14 Cash Leakage Watchlist",
    "color": "#ef4444",
    "icon": "shopping-cart",
    "autoAssignable": false
  },
  {
    "name": "Marketing / Ads",
    "parent": "11 Work & Business",
    "color": "#9333ea",
    "icon": "megaphone",
    "autoAssignable": true
  },
  {
    "name": "Books & Hobbies",
    "parent": "03 Spend-it Wants",
    "color": "#f97316",
    "icon": "book-open",
    "autoAssignable": true
  },
  {
    "name": "Emergency Fund Top-up",
    "parent": "06 Planned Needs",
    "color": "#0891b2",
    "icon": "shield-plus",
    "autoAssignable": true
  },
  {
    "name": "Index Fund Investment",
    "parent": "08 Invest-it",
    "color": "#0f766e",
    "icon": "chart-no-axes-combined",
    "autoAssignable": true
  },
  {
    "name": "Electricity",
    "parent": "02 Spend-it Needs",
    "color": "#2563eb",
    "icon": "zap",
    "autoAssignable": true
  },
  {
    "name": "Capital Gains Realized",
    "parent": "01 Income",
    "color": "#16a34a",
    "icon": "line-chart",
    "autoAssignable": true
  },
  {
    "name": "Taxi / Cab / Auto",
    "parent": "02 Spend-it Needs",
    "color": "#2563eb",
    "icon": "car-taxi-front",
    "autoAssignable": true
  },
  {
    "name": "Medical Visits",
    "parent": "02 Spend-it Needs",
    "color": "#2563eb",
    "icon": "stethoscope",
    "autoAssignable": true
  },
  {
    "name": "Upstox Holdings",
    "parent": "09 Assets & Net Worth",
    "color": "#475569",
    "icon": "bar-chart",
    "autoAssignable": true
  },
  {
    "name": "Home Maintenance",
    "parent": "02 Spend-it Needs",
    "color": "#2563eb",
    "icon": "hammer",
    "autoAssignable": true
  },
  {
    "name": "Credit Card Purchase",
    "parent": "05 Debt & Credit",
    "color": "#7c3aed",
    "icon": "credit-card",
    "autoAssignable": true
  },
  {
    "name": "Income to Spend-it Transfer",
    "parent": "10 Transfers & Adjustments",
    "color": "#64748b",
    "icon": "arrow-right-left",
    "autoAssignable": true
  },
  {
    "name": "Spend-it to Income Transfer",
    "parent": "10 Transfers & Adjustments",
    "color": "#64748b",
    "icon": "arrow-left-right",
    "autoAssignable": true
  },
  {
    "name": "Home Decor Upgrade",
    "parent": "07 Planned Wants",
    "color": "#ec4899",
    "icon": "sofa",
    "autoAssignable": true
  },
  {
    "name": "Credit Card Fees",
    "parent": "05 Debt & Credit",
    "color": "#7c3aed",
    "icon": "badge-indian-rupee",
    "autoAssignable": true
  },
  {
    "name": "Equity Purchase",
    "parent": "08 Invest-it",
    "color": "#0f766e",
    "icon": "candlestick-chart",
    "autoAssignable": true
  },
  {
    "name": "Liquid Fund Parking",
    "parent": "08 Invest-it",
    "color": "#0f766e",
    "icon": "droplet",
    "autoAssignable": true
  },
  {
    "name": "Salary",
    "parent": "01 Income",
    "color": "#16a34a",
    "icon": "briefcase",
    "autoAssignable": true
  },
  {
    "name": "Canva / Design Tools",
    "parent": "11 Work & Business",
    "color": "#9333ea",
    "icon": "palette",
    "autoAssignable": true
  },
  {
    "name": "Consultants / Freelancers",
    "parent": "11 Work & Business",
    "color": "#9333ea",
    "icon": "users",
    "autoAssignable": true
  },
  {
    "name": "Gadget Leakage",
    "parent": "14 Cash Leakage Watchlist",
    "color": "#ef4444",
    "icon": "smartphone",
    "autoAssignable": false
  },
  {
    "name": "Reimbursements",
    "parent": "01 Income",
    "color": "#16a34a",
    "icon": "receipt",
    "autoAssignable": true
  },
  {
    "name": "Travel Upgrade",
    "parent": "07 Planned Wants",
    "color": "#ec4899",
    "icon": "luggage",
    "autoAssignable": true
  },
  {
    "name": "10 Transfers & Adjustments",
    "parent": null,
    "color": "#64748b",
    "icon": "repeat",
    "autoAssignable": true
  },
  {
    "name": "Cloud Hosting",
    "parent": "11 Work & Business",
    "color": "#9333ea",
    "icon": "cloud",
    "autoAssignable": true
  },
  {
    "name": "Tickertape Gold / Assets",
    "parent": "09 Assets & Net Worth",
    "color": "#475569",
    "icon": "coins",
    "autoAssignable": true
  },
  {
    "name": "Credit Card Payment",
    "parent": "05 Debt & Credit",
    "color": "#7c3aed",
    "icon": "receipt",
    "autoAssignable": true
  },
  {
    "name": "Bad Debt / Write-off",
    "parent": "05 Debt & Credit",
    "color": "#7c3aed",
    "icon": "x-circle",
    "autoAssignable": true
  },
  {
    "name": "Unplanned Travel Leakage",
    "parent": "14 Cash Leakage Watchlist",
    "color": "#ef4444",
    "icon": "map",
    "autoAssignable": false
  },
  {
    "name": "Dividend Income",
    "parent": "01 Income",
    "color": "#16a34a",
    "icon": "coins",
    "autoAssignable": true
  },
  {
    "name": "12 Taxes & Compliance",
    "parent": null,
    "color": "#ca8a04",
    "icon": "file-text",
    "autoAssignable": true
  },
  {
    "name": "Public Transport",
    "parent": "02 Spend-it Needs",
    "color": "#2563eb",
    "icon": "bus",
    "autoAssignable": true
  },
  {
    "name": "Vehicle Value",
    "parent": "09 Assets & Net Worth",
    "color": "#475569",
    "icon": "car",
    "autoAssignable": true
  },
  {
    "name": "Shopping Personal",
    "parent": "03 Spend-it Wants",
    "color": "#f97316",
    "icon": "shopping-bag",
    "autoAssignable": true
  },
  {
    "name": "Freelance Income",
    "parent": "01 Income",
    "color": "#16a34a",
    "icon": "paintbrush",
    "autoAssignable": true
  },
  {
    "name": "Stock Images / Mockups",
    "parent": "11 Work & Business",
    "color": "#9333ea",
    "icon": "image",
    "autoAssignable": true
  },
  {
    "name": "Premium Phone Upgrade",
    "parent": "07 Planned Wants",
    "color": "#ec4899",
    "icon": "smartphone",
    "autoAssignable": true
  },
  {
    "name": "Clothing Non-essential",
    "parent": "03 Spend-it Wants",
    "color": "#f97316",
    "icon": "shirt",
    "autoAssignable": true
  },
  {
    "name": "Cash Deposit",
    "parent": "10 Transfers & Adjustments",
    "color": "#64748b",
    "icon": "wallet",
    "autoAssignable": true
  },
  {
    "name": "Small Cash Unknown",
    "parent": "14 Cash Leakage Watchlist",
    "color": "#ef4444",
    "icon": "circle-help",
    "autoAssignable": false
  },
  {
    "name": "Charity / Donation",
    "parent": "13 Family & Giving",
    "color": "#be123c",
    "icon": "hand-heart",
    "autoAssignable": true
  },
  {
    "name": "Jewellery / Physical Gold",
    "parent": "09 Assets & Net Worth",
    "color": "#475569",
    "icon": "gem",
    "autoAssignable": true
  },
  {
    "name": "Stable Money Investment",
    "parent": "08 Invest-it",
    "color": "#0f766e",
    "icon": "badge-indian-rupee",
    "autoAssignable": true
  },
  {
    "name": "Debt Settlement",
    "parent": "05 Debt & Credit",
    "color": "#7c3aed",
    "icon": "check-circle",
    "autoAssignable": true
  },
  {
    "name": "Bank Balance Snapshot",
    "parent": "09 Assets & Net Worth",
    "color": "#475569",
    "icon": "landmark",
    "autoAssignable": true
  },
  {
    "name": "Repairs Essential",
    "parent": "02 Spend-it Needs",
    "color": "#2563eb",
    "icon": "wrench",
    "autoAssignable": true
  },
  {
    "name": "Medical Help To Others",
    "parent": "13 Family & Giving",
    "color": "#be123c",
    "icon": "heart-pulse",
    "autoAssignable": true
  },
  {
    "name": "Critical Illness Cover",
    "parent": "04 Protect",
    "color": "#dc2626",
    "icon": "shield-plus",
    "autoAssignable": true
  },
  {
    "name": "Credit Card Interest Leakage",
    "parent": "14 Cash Leakage Watchlist",
    "color": "#ef4444",
    "icon": "percent",
    "autoAssignable": false
  },
  {
    "name": "Uncategorized Review",
    "parent": "10 Transfers & Adjustments",
    "color": "#64748b",
    "icon": "circle-help",
    "autoAssignable": true
  },
  {
    "name": "GST Payment",
    "parent": "12 Taxes & Compliance",
    "color": "#ca8a04",
    "icon": "receipt-text",
    "autoAssignable": true
  },
  {
    "name": "NPS Contribution",
    "parent": "08 Invest-it",
    "color": "#0f766e",
    "icon": "tree-pine",
    "autoAssignable": true
  },
  {
    "name": "Vegetables & Fruits",
    "parent": "02 Spend-it Needs",
    "color": "#2563eb",
    "icon": "apple",
    "autoAssignable": true
  },
  {
    "name": "Camera / Creative Gear",
    "parent": "07 Planned Wants",
    "color": "#ec4899",
    "icon": "camera",
    "autoAssignable": true
  },
  {
    "name": "Retainer Income",
    "parent": "01 Income",
    "color": "#16a34a",
    "icon": "calendar-days",
    "autoAssignable": true
  },
  {
    "name": "Receivables",
    "parent": "09 Assets & Net Worth",
    "color": "#475569",
    "icon": "file-plus",
    "autoAssignable": true
  },
  {
    "name": "Digital Gold Sale",
    "parent": "08 Invest-it",
    "color": "#0f766e",
    "icon": "coins",
    "autoAssignable": true
  },
  {
    "name": "Payables",
    "parent": "09 Assets & Net Worth",
    "color": "#475569",
    "icon": "file-minus",
    "autoAssignable": true
  },
  {
    "name": "UPI Transfer Between Own Accounts",
    "parent": "10 Transfers & Adjustments",
    "color": "#64748b",
    "icon": "smartphone",
    "autoAssignable": true
  },
  {
    "name": "OTT / Entertainment",
    "parent": "03 Spend-it Wants",
    "color": "#f97316",
    "icon": "tv",
    "autoAssignable": true
  },
  {
    "name": "Family Medical Emergency",
    "parent": "04 Protect",
    "color": "#dc2626",
    "icon": "hospital",
    "autoAssignable": true
  },
  {
    "name": "06 Planned Needs",
    "parent": null,
    "color": "#0891b2",
    "icon": "calendar-check",
    "autoAssignable": true
  },
  {
    "name": "Debt Prepayment",
    "parent": "05 Debt & Credit",
    "color": "#7c3aed",
    "icon": "scissors",
    "autoAssignable": true
  },
  {
    "name": "Coworking / Office",
    "parent": "11 Work & Business",
    "color": "#9333ea",
    "icon": "building-2",
    "autoAssignable": true
  },
  {
    "name": "Manual Correction Needed",
    "parent": "15 Review Buckets",
    "color": "#334155",
    "icon": "pencil",
    "autoAssignable": false
  },
  {
    "name": "Water",
    "parent": "02 Spend-it Needs",
    "color": "#2563eb",
    "icon": "droplets",
    "autoAssignable": true
  },
  {
    "name": "02 Spend-it Needs",
    "parent": null,
    "color": "#2563eb",
    "icon": "home",
    "autoAssignable": true
  },
  {
    "name": "Sale / Discount Impulse",
    "parent": "14 Cash Leakage Watchlist",
    "color": "#ef4444",
    "icon": "tag",
    "autoAssignable": false
  },
  {
    "name": "Dining Social",
    "parent": "03 Spend-it Wants",
    "color": "#f97316",
    "icon": "wine",
    "autoAssignable": true
  },
  {
    "name": "Phone Replacement Essential",
    "parent": "06 Planned Needs",
    "color": "#0891b2",
    "icon": "smartphone",
    "autoAssignable": true
  },
  {
    "name": "SIP Mutual Fund",
    "parent": "08 Invest-it",
    "color": "#0f766e",
    "icon": "trending-up",
    "autoAssignable": true
  },
  {
    "name": "Luxury Purchase Fund",
    "parent": "07 Planned Wants",
    "color": "#ec4899",
    "icon": "gem",
    "autoAssignable": true
  },
  {
    "name": "Loan Insurance",
    "parent": "05 Debt & Credit",
    "color": "#7c3aed",
    "icon": "shield",
    "autoAssignable": true
  },
  {
    "name": "AI Tools",
    "parent": "11 Work & Business",
    "color": "#9333ea",
    "icon": "bot",
    "autoAssignable": true
  },
  {
    "name": "Health Insurance Premium",
    "parent": "04 Protect",
    "color": "#dc2626",
    "icon": "heart-pulse",
    "autoAssignable": true
  },
  {
    "name": "Spouse / Household Shared Expenses",
    "parent": "02 Spend-it Needs",
    "color": "#2563eb",
    "icon": "users",
    "autoAssignable": true
  },
  {
    "name": "Retirement Investing",
    "parent": "08 Invest-it",
    "color": "#0f766e",
    "icon": "hourglass",
    "autoAssignable": true
  },
  {
    "name": "Cafes Leakage",
    "parent": "14 Cash Leakage Watchlist",
    "color": "#ef4444",
    "icon": "coffee",
    "autoAssignable": false
  },
  {
    "name": "Bank Charges",
    "parent": "02 Spend-it Needs",
    "color": "#2563eb",
    "icon": "landmark",
    "autoAssignable": true
  },
  {
    "name": "Medical Emergency",
    "parent": "04 Protect",
    "color": "#dc2626",
    "icon": "ambulance",
    "autoAssignable": true
  },
  {
    "name": "Milk & Dairy",
    "parent": "02 Spend-it Needs",
    "color": "#2563eb",
    "icon": "milk",
    "autoAssignable": true
  },
  {
    "name": "Annual Insurance Premium",
    "parent": "06 Planned Needs",
    "color": "#0891b2",
    "icon": "calendar-check",
    "autoAssignable": true
  },
  {
    "name": "CA / Tax Filing Fee",
    "parent": "12 Taxes & Compliance",
    "color": "#ca8a04",
    "icon": "file-check",
    "autoAssignable": true
  },
  {
    "name": "Credit Card Bill Payment Transfer",
    "parent": "10 Transfers & Adjustments",
    "color": "#64748b",
    "icon": "credit-card",
    "autoAssignable": true
  },
  {
    "name": "Opening Balance",
    "parent": "10 Transfers & Adjustments",
    "color": "#64748b",
    "icon": "circle-plus",
    "autoAssignable": true
  },
  {
    "name": "Vacation Fund",
    "parent": "07 Planned Wants",
    "color": "#ec4899",
    "icon": "plane",
    "autoAssignable": true
  },
  {
    "name": "05 Debt & Credit",
    "parent": null,
    "color": "#7c3aed",
    "icon": "credit-card",
    "autoAssignable": true
  },
  {
    "name": "Dental / Eye Care Planned",
    "parent": "06 Planned Needs",
    "color": "#0891b2",
    "icon": "eye",
    "autoAssignable": true
  },
  {
    "name": "Term Insurance Premium",
    "parent": "04 Protect",
    "color": "#dc2626",
    "icon": "umbrella",
    "autoAssignable": true
  },
  {
    "name": "Refund Adjustment",
    "parent": "10 Transfers & Adjustments",
    "color": "#64748b",
    "icon": "undo-2",
    "autoAssignable": true
  },
  {
    "name": "Wardrobe Upgrade",
    "parent": "07 Planned Wants",
    "color": "#ec4899",
    "icon": "shirt",
    "autoAssignable": true
  },
  {
    "name": "Fixed Deposit",
    "parent": "08 Invest-it",
    "color": "#0f766e",
    "icon": "piggy-bank",
    "autoAssignable": true
  },
  {
    "name": "Medicines",
    "parent": "02 Spend-it Needs",
    "color": "#2563eb",
    "icon": "pill",
    "autoAssignable": true
  },
  {
    "name": "STT / Transaction Taxes",
    "parent": "08 Invest-it",
    "color": "#0f766e",
    "icon": "file-text",
    "autoAssignable": true
  },
  {
    "name": "Credit Card Interest",
    "parent": "05 Debt & Credit",
    "color": "#7c3aed",
    "icon": "percent",
    "autoAssignable": true
  },
  {
    "name": "PPF Contribution",
    "parent": "08 Invest-it",
    "color": "#0f766e",
    "icon": "shield",
    "autoAssignable": true
  },
  {
    "name": "Dining Experience Fund",
    "parent": "07 Planned Wants",
    "color": "#ec4899",
    "icon": "utensils",
    "autoAssignable": true
  },
  {
    "name": "EPF / PF Contribution",
    "parent": "08 Invest-it",
    "color": "#0f766e",
    "icon": "briefcase",
    "autoAssignable": true
  },
  {
    "name": "GST / Compliance Service",
    "parent": "11 Work & Business",
    "color": "#9333ea",
    "icon": "file-text",
    "autoAssignable": true
  },
  {
    "name": "Debt Review",
    "parent": "15 Review Buckets",
    "color": "#334155",
    "icon": "credit-card",
    "autoAssignable": false
  },
  {
    "name": "Gifts Non-essential",
    "parent": "03 Spend-it Wants",
    "color": "#f97316",
    "icon": "gift",
    "autoAssignable": true
  },
  {
    "name": "Business Reimbursement Paid",
    "parent": "11 Work & Business",
    "color": "#9333ea",
    "icon": "receipt",
    "autoAssignable": true
  },
  {
    "name": "Bonus",
    "parent": "01 Income",
    "color": "#16a34a",
    "icon": "badge-indian-rupee",
    "autoAssignable": true
  },
  {
    "name": "Hobby Equipment",
    "parent": "07 Planned Wants",
    "color": "#ec4899",
    "icon": "palette",
    "autoAssignable": true
  },
  {
    "name": "Investment Review",
    "parent": "15 Review Buckets",
    "color": "#334155",
    "icon": "line-chart",
    "autoAssignable": false
  },
  {
    "name": "Education Essentials",
    "parent": "02 Spend-it Needs",
    "color": "#2563eb",
    "icon": "graduation-cap",
    "autoAssignable": true
  },
  {
    "name": "Vehicle Loan EMI",
    "parent": "05 Debt & Credit",
    "color": "#7c3aed",
    "icon": "car",
    "autoAssignable": true
  },
  {
    "name": "Category Rule Needed",
    "parent": "15 Review Buckets",
    "color": "#334155",
    "icon": "settings",
    "autoAssignable": false
  },
  {
    "name": "Bonds / Fixed Income",
    "parent": "08 Invest-it",
    "color": "#0f766e",
    "icon": "file-lock",
    "autoAssignable": true
  },
  {
    "name": "Penalty / Interest Tax",
    "parent": "12 Taxes & Compliance",
    "color": "#ca8a04",
    "icon": "alert-triangle",
    "autoAssignable": true
  },
  {
    "name": "Books for Work",
    "parent": "11 Work & Business",
    "color": "#9333ea",
    "icon": "book-open",
    "autoAssignable": true
  },
  {
    "name": "Spouse Support / Shared",
    "parent": "13 Family & Giving",
    "color": "#be123c",
    "icon": "users",
    "autoAssignable": true
  },
  {
    "name": "14 Cash Leakage Watchlist",
    "parent": null,
    "color": "#ef4444",
    "icon": "alarm-clock",
    "autoAssignable": false
  },
  {
    "name": "Audit / Compliance",
    "parent": "12 Taxes & Compliance",
    "color": "#ca8a04",
    "icon": "clipboard-check",
    "autoAssignable": true
  },
  {
    "name": "Legal / Compliance Cost",
    "parent": "06 Planned Needs",
    "color": "#0891b2",
    "icon": "scale",
    "autoAssignable": true
  },
  {
    "name": "Domain & Email",
    "parent": "11 Work & Business",
    "color": "#9333ea",
    "icon": "globe",
    "autoAssignable": true
  },
  {
    "name": "04 Protect",
    "parent": null,
    "color": "#dc2626",
    "icon": "shield-check",
    "autoAssignable": true
  },
  {
    "name": "Bank Charges Business",
    "parent": "11 Work & Business",
    "color": "#9333ea",
    "icon": "landmark",
    "autoAssignable": true
  },
  {
    "name": "Other Income",
    "parent": "01 Income",
    "color": "#16a34a",
    "icon": "plus-circle",
    "autoAssignable": true
  },
  {
    "name": "Cash Gifts Received",
    "parent": "01 Income",
    "color": "#16a34a",
    "icon": "gift",
    "autoAssignable": true
  },
  {
    "name": "Parking & Tolls",
    "parent": "02 Spend-it Needs",
    "color": "#2563eb",
    "icon": "parking-circle",
    "autoAssignable": true
  },
  {
    "name": "Fuel",
    "parent": "02 Spend-it Needs",
    "color": "#2563eb",
    "icon": "fuel",
    "autoAssignable": true
  },
  {
    "name": "Family Obligation Planned",
    "parent": "06 Planned Needs",
    "color": "#0891b2",
    "icon": "users",
    "autoAssignable": true
  },
  {
    "name": "Creative Experiment Fund",
    "parent": "07 Planned Wants",
    "color": "#ec4899",
    "icon": "sparkles",
    "autoAssignable": true
  },
  {
    "name": "Government Fees",
    "parent": "12 Taxes & Compliance",
    "color": "#ca8a04",
    "icon": "building",
    "autoAssignable": true
  },
  {
    "name": "Capital Gains Tax Reserve",
    "parent": "12 Taxes & Compliance",
    "color": "#ca8a04",
    "icon": "line-chart",
    "autoAssignable": true
  },
  {
    "name": "Business Reimbursement Received",
    "parent": "11 Work & Business",
    "color": "#9333ea",
    "icon": "undo-2",
    "autoAssignable": true
  },
  {
    "name": "Shoes & Accessories",
    "parent": "03 Spend-it Wants",
    "color": "#f97316",
    "icon": "watch",
    "autoAssignable": true
  },
  {
    "name": "Education Help To Others",
    "parent": "13 Family & Giving",
    "color": "#be123c",
    "icon": "graduation-cap",
    "autoAssignable": true
  },
  {
    "name": "TDS / TCS",
    "parent": "12 Taxes & Compliance",
    "color": "#ca8a04",
    "icon": "file-search",
    "autoAssignable": true
  }
];

export const SEED_RULES: SeedRule[] = [
  {
    "priority": 1,
    "match": "SALARY",
    "category": "Salary"
  },
  {
    "priority": 2,
    "match": "INT.PD",
    "category": "Interest Income"
  },
  {
    "priority": 3,
    "match": "SB INT",
    "category": "Interest Income"
  },
  {
    "priority": 4,
    "match": "FD INT",
    "category": "Interest Income"
  },
  {
    "priority": 5,
    "match": "INTEREST CR",
    "category": "Interest Income"
  },
  {
    "priority": 6,
    "match": "DIVIDEND",
    "category": "Dividend Income"
  },
  {
    "priority": 7,
    "match": "CASHBACK",
    "category": "Refunds Received"
  },
  {
    "priority": 8,
    "match": "REFUND",
    "category": "Refunds Received"
  },
  {
    "priority": 9,
    "match": "MSEDCL",
    "category": "Electricity"
  },
  {
    "priority": 10,
    "match": "TATA POWER",
    "category": "Electricity"
  },
  {
    "priority": 11,
    "match": "ADANI ELECTRICITY",
    "category": "Electricity"
  },
  {
    "priority": 12,
    "match": "BESCOM",
    "category": "Electricity"
  },
  {
    "priority": 13,
    "match": "ELECTRICITY",
    "category": "Electricity"
  },
  {
    "priority": 14,
    "match": "MAHANAGAR GAS",
    "category": "Gas"
  },
  {
    "priority": 15,
    "match": "INDRAPRASTHA GAS",
    "category": "Gas"
  },
  {
    "priority": 16,
    "match": "GUJARAT GAS",
    "category": "Gas"
  },
  {
    "priority": 17,
    "match": "BWSSB",
    "category": "Water"
  },
  {
    "priority": 18,
    "match": "WATER BILL",
    "category": "Water"
  },
  {
    "priority": 19,
    "match": "AIRTEL",
    "category": "Mobile Phone"
  },
  {
    "priority": 20,
    "match": "JIO",
    "category": "Mobile Phone"
  },
  {
    "priority": 21,
    "match": "VI POSTPAID",
    "category": "Mobile Phone"
  },
  {
    "priority": 22,
    "match": "VODAFONE IDEA",
    "category": "Mobile Phone"
  },
  {
    "priority": 23,
    "match": "ACT FIBERNET",
    "category": "Internet / WiFi"
  },
  {
    "priority": 24,
    "match": "TIKONA",
    "category": "Internet / WiFi"
  },
  {
    "priority": 25,
    "match": "HATHWAY",
    "category": "Internet / WiFi"
  },
  {
    "priority": 26,
    "match": "BIGBASKET",
    "category": "Groceries"
  },
  {
    "priority": 27,
    "match": "BLINKIT",
    "category": "Groceries"
  },
  {
    "priority": 28,
    "match": "ZEPTO",
    "category": "Groceries"
  },
  {
    "priority": 29,
    "match": "DMART",
    "category": "Groceries"
  },
  {
    "priority": 30,
    "match": "RELIANCE FRESH",
    "category": "Groceries"
  },
  {
    "priority": 31,
    "match": "MORE SUPER",
    "category": "Groceries"
  },
  {
    "priority": 32,
    "match": "INDIAN OIL",
    "category": "Fuel"
  },
  {
    "priority": 33,
    "match": "BHARAT PETROLEUM",
    "category": "Fuel"
  },
  {
    "priority": 34,
    "match": "HPCL",
    "category": "Fuel"
  },
  {
    "priority": 35,
    "match": "RELIANCE PETROL",
    "category": "Fuel"
  },
  {
    "priority": 36,
    "match": "SHELL",
    "category": "Fuel"
  },
  {
    "priority": 37,
    "match": "UBER",
    "category": "Taxi / Cab / Auto"
  },
  {
    "priority": 38,
    "match": "OLA",
    "category": "Taxi / Cab / Auto"
  },
  {
    "priority": 39,
    "match": "RAPIDO",
    "category": "Taxi / Cab / Auto"
  },
  {
    "priority": 40,
    "match": "FASTAG",
    "category": "Parking & Tolls"
  },
  {
    "priority": 41,
    "match": "TOLL",
    "category": "Parking & Tolls"
  },
  {
    "priority": 42,
    "match": "BMRCL",
    "category": "Public Transport"
  },
  {
    "priority": 43,
    "match": "DMRC",
    "category": "Public Transport"
  },
  {
    "priority": 44,
    "match": "IRCTC",
    "category": "Public Transport"
  },
  {
    "priority": 45,
    "match": "AMC CHARGES",
    "category": "Bank Charges"
  },
  {
    "priority": 46,
    "match": "SMS CHARGES",
    "category": "Bank Charges"
  },
  {
    "priority": 47,
    "match": "MIN.BAL",
    "category": "Bank Charges"
  },
  {
    "priority": 48,
    "match": "NEFT CHARGES",
    "category": "Bank Charges"
  },
  {
    "priority": 49,
    "match": "APOLLO PHARMACY",
    "category": "Medicines"
  },
  {
    "priority": 50,
    "match": "1MG",
    "category": "Medicines"
  },
  {
    "priority": 51,
    "match": "PHARMEASY",
    "category": "Medicines"
  },
  {
    "priority": 52,
    "match": "NETMEDS",
    "category": "Medicines"
  },
  {
    "priority": 53,
    "match": "PRACTO",
    "category": "Medical Visits"
  },
  {
    "priority": 54,
    "match": "SWIGGY",
    "category": "Food Delivery"
  },
  {
    "priority": 55,
    "match": "ZOMATO",
    "category": "Food Delivery"
  },
  {
    "priority": 56,
    "match": "EATSURE",
    "category": "Food Delivery"
  },
  {
    "priority": 57,
    "match": "STARBUCKS",
    "category": "Coffee / Cafes"
  },
  {
    "priority": 58,
    "match": "BLUE TOKAI",
    "category": "Coffee / Cafes"
  },
  {
    "priority": 59,
    "match": "THIRD WAVE",
    "category": "Coffee / Cafes"
  },
  {
    "priority": 60,
    "match": "AMAZON",
    "category": "Shopping Personal"
  },
  {
    "priority": 61,
    "match": "FLIPKART",
    "category": "Shopping Personal"
  },
  {
    "priority": 62,
    "match": "MYNTRA",
    "category": "Clothing Non-essential"
  },
  {
    "priority": 63,
    "match": "AJIO",
    "category": "Clothing Non-essential"
  },
  {
    "priority": 64,
    "match": "NYKAA",
    "category": "Beauty / Grooming"
  },
  {
    "priority": 65,
    "match": "BOOKMYSHOW",
    "category": "Movies / Events"
  },
  {
    "priority": 66,
    "match": "PVR",
    "category": "Movies / Events"
  },
  {
    "priority": 67,
    "match": "INOX",
    "category": "Movies / Events"
  },
  {
    "priority": 68,
    "match": "NETFLIX",
    "category": "OTT / Entertainment"
  },
  {
    "priority": 69,
    "match": "HOTSTAR",
    "category": "OTT / Entertainment"
  },
  {
    "priority": 70,
    "match": "PRIME VIDEO",
    "category": "OTT / Entertainment"
  },
  {
    "priority": 71,
    "match": "SPOTIFY",
    "category": "OTT / Entertainment"
  },
  {
    "priority": 72,
    "match": "YOUTUBE PREMIUM",
    "category": "OTT / Entertainment"
  },
  {
    "priority": 73,
    "match": "APPLE.COM/BILL",
    "category": "Apps & Digital Subscriptions"
  },
  {
    "priority": 74,
    "match": "GOOGLE *YOUTUBE",
    "category": "OTT / Entertainment"
  },
  {
    "priority": 75,
    "match": "MAKEMYTRIP",
    "category": "Vacation Spend"
  },
  {
    "priority": 76,
    "match": "GOIBIBO",
    "category": "Vacation Spend"
  },
  {
    "priority": 77,
    "match": "BOOKING.COM",
    "category": "Vacation Spend"
  },
  {
    "priority": 78,
    "match": "AIRBNB",
    "category": "Vacation Spend"
  },
  {
    "priority": 79,
    "match": "INDIGO",
    "category": "Vacation Spend"
  },
  {
    "priority": 80,
    "match": "VISTARA",
    "category": "Vacation Spend"
  },
  {
    "priority": 81,
    "match": "LIC OF INDIA",
    "category": "Term Insurance Premium"
  },
  {
    "priority": 82,
    "match": "HDFC LIFE",
    "category": "Term Insurance Premium"
  },
  {
    "priority": 83,
    "match": "STAR HEALTH",
    "category": "Health Insurance Premium"
  },
  {
    "priority": 84,
    "match": "HDFC ERGO",
    "category": "Health Insurance Premium"
  },
  {
    "priority": 85,
    "match": "ICICI LOMBARD",
    "category": "Health Insurance Premium"
  },
  {
    "priority": 86,
    "match": "MAX BUPA",
    "category": "Health Insurance Premium"
  },
  {
    "priority": 87,
    "match": "NIVA BUPA",
    "category": "Health Insurance Premium"
  },
  {
    "priority": 88,
    "match": "BAJAJ ALLIANZ",
    "category": "Vehicle Insurance Premium"
  },
  {
    "priority": 89,
    "match": "CREDIT CARD PAYMENT",
    "category": "Credit Card Payment"
  },
  {
    "priority": 90,
    "match": "CC BILL PAYMENT",
    "category": "Credit Card Payment"
  },
  {
    "priority": 91,
    "match": "BILLDESK CREDIT CARD",
    "category": "Credit Card Payment"
  },
  {
    "priority": 92,
    "match": "EMI",
    "category": "Personal Loan EMI"
  },
  {
    "priority": 93,
    "match": "ZERODHA",
    "category": "Investment Funding Transfer"
  },
  {
    "priority": 94,
    "match": "GROWW",
    "category": "Investment Funding Transfer"
  },
  {
    "priority": 95,
    "match": "UPSTOX",
    "category": "Investment Funding Transfer"
  },
  {
    "priority": 96,
    "match": "BSE STAR MF",
    "category": "SIP Mutual Fund"
  },
  {
    "priority": 97,
    "match": "SIP",
    "category": "SIP Mutual Fund"
  },
  {
    "priority": 98,
    "match": "MUTUAL FUND",
    "category": "SIP Mutual Fund"
  },
  {
    "priority": 99,
    "match": "PPF",
    "category": "PPF Contribution"
  },
  {
    "priority": 100,
    "match": "NPS",
    "category": "NPS Contribution"
  },
  {
    "priority": 101,
    "match": "SAFEGOLD",
    "category": "Digital Gold Purchase"
  },
  {
    "priority": 102,
    "match": "MMTC PAMP",
    "category": "Digital Gold Purchase"
  },
  {
    "priority": 103,
    "match": "ATM WDL",
    "category": "Cash Withdrawal"
  },
  {
    "priority": 104,
    "match": "NWD-",
    "category": "Cash Withdrawal"
  },
  {
    "priority": 105,
    "match": "ATM CASH",
    "category": "Cash Withdrawal"
  },
  {
    "priority": 106,
    "match": "CASH DEPOSIT",
    "category": "Cash Deposit"
  },
  {
    "priority": 107,
    "match": "TDS",
    "category": "TDS / TCS"
  },
  {
    "priority": 108,
    "match": "INCOME TAX",
    "category": "Income Tax Payment"
  },
  {
    "priority": 109,
    "match": "ADVANCE TAX",
    "category": "Advance Tax"
  },
  {
    "priority": 110,
    "match": "GST PAYMENT",
    "category": "GST Payment"
  }
];

export const SEED_ACCOUNTS: SeedAccount[] = [
  {
    "name": "SBI Savings",
    "institution": "SBI",
    "kind": "bank"
  },
  {
    "name": "Federal Bank Savings",
    "institution": "FEDERAL",
    "kind": "bank"
  },
  {
    "name": "IDFC FIRST Savings",
    "institution": "IDFC_BANK",
    "kind": "bank"
  },
  {
    "name": "IDFC FIRST Credit Card",
    "institution": "IDFC_CC",
    "kind": "credit_card"
  },
  {
    "name": "Suryoday Credit Card",
    "institution": "SURYODAY_CC",
    "kind": "credit_card"
  },
  {
    "name": "HDFC — Sample",
    "institution": "HDFC",
    "kind": "bank"
  },
  {
    "name": "Zerodha",
    "institution": "ZERODHA",
    "kind": "broker"
  },
  {
    "name": "Upstox",
    "institution": "UPSTOX",
    "kind": "broker"
  }
];

export const TAXONOMY_NAME_SET: ReadonlySet<string> = new Set(SEED_CATEGORIES.map((c) => c.name));
