import { readFileSync, writeFileSync } from "node:fs";
import { loadTaxonomy, loadRules } from "../src/lib/ingest/rules.js";

/**
 * Generates supabase/seed/seed.sql from the Halan taxonomy CSV and vendor rules YAML.
 * Run AFTER first sign-in; replace :USER_ID with your auth.users id, or run via the
 * app's one-time bootstrap which substitutes the session user automatically.
 * Validations (loadTaxonomy / loadRules) run first — generation refuses on any
 * Leakage/Review auto-assign rule or unknown category. Guard rails are also baked
 * into the data: auto_assignable=false for every leaf under parents 14 and 15.
 */
const taxonomy = loadTaxonomy(readFileSync("supabase/seed/taxonomy_master_from_sure.csv", "utf8"));
const rules = loadRules(readFileSync("supabase/seed/vendor_to_category_starter.yaml", "utf8"), taxonomy);

const esc = (s: string) => s.replace(/'/g, "''");
const lines: string[] = [
  "-- generated by scripts/generate-seed.ts — do not edit by hand",
  "-- replace :USER_ID before running, e.g. \\set USER_ID '...uuid...'",
  "begin;",
];

// parents first (parent = ''), then leaves referencing parent by name
const cats = [...taxonomy.values()];
const parents = cats.filter((c) => !c.parent);
const leaves = cats.filter((c) => c.parent);
const NO_AUTO = new Set(["14 Cash Leakage Watchlist", "15 Review Buckets"]);

for (const p of parents) {
  lines.push(
    `insert into public.categories (user_id, name, color, lucide_icon, auto_assignable) values (:'USER_ID', '${esc(p.name)}', '${esc(p.color)}', '${esc(p.icon)}', ${NO_AUTO.has(p.name) ? "false" : "true"});`,
  );
}
for (const l of leaves) {
  const autoOk = !NO_AUTO.has(l.parent) || l.name === "Uncategorized Review" ? !NO_AUTO.has(l.parent) : false;
  lines.push(
    `insert into public.categories (user_id, name, parent_id, color, lucide_icon, auto_assignable) ` +
    `select :'USER_ID', '${esc(l.name)}', id, '${esc(l.color)}', '${esc(l.icon)}', ${autoOk} from public.categories where user_id = :'USER_ID' and name = '${esc(l.parent)}';`,
  );
}

rules.forEach((r, i) => {
  lines.push(
    `insert into public.vendor_rules (user_id, priority, match_text, category_id) ` +
    `select :'USER_ID', ${i + 1}, '${esc(r.match)}', id from public.categories where user_id = :'USER_ID' and name = '${esc(r.category)}';`,
  );
});

lines.push("commit;");
writeFileSync("supabase/seed/seed.sql", lines.join("\n") + "\n");
console.log(`seed.sql written: ${parents.length} parents, ${leaves.length} leaves, ${rules.length} rules`);
console.log(`auto_assignable=false enforced for all leaves under: ${[...NO_AUTO].join(" | ")}`);
