import { readFileSync, writeFileSync } from "node:fs";
import { loadTaxonomy, loadRules } from "../src/lib/ingest/rules.js";

/**
 * Emits src/lib/seed-data.ts (committed, build-safe — no runtime fs on Vercel).
 * Reuses the validated loaders, so generation refuses on any Leakage/Review auto-rule
 * or unknown category, exactly like the SQL seed path.
 */
const taxonomy = loadTaxonomy(readFileSync("supabase/seed/taxonomy_master_from_sure.csv", "utf8"));
const rules = loadRules(readFileSync("supabase/seed/vendor_to_category_starter.yaml", "utf8"), taxonomy);

const NO_AUTO = new Set(["14 Cash Leakage Watchlist", "15 Review Buckets"]);
const cats = [...taxonomy.values()].map((c) => ({
  name: c.name,
  parent: c.parent || null,
  color: c.color,
  icon: c.icon,
  autoAssignable: !(NO_AUTO.has(c.parent) || NO_AUTO.has(c.name)),
}));

const ACCOUNTS = [
  { name: "SBI Savings", institution: "SBI", kind: "bank" },
  { name: "Federal Bank Savings", institution: "FEDERAL", kind: "bank" },
  { name: "IDFC FIRST Savings", institution: "IDFC_BANK", kind: "bank" },
  { name: "IDFC FIRST Credit Card", institution: "IDFC_CC", kind: "credit_card" },
  { name: "Suryoday Credit Card", institution: "SURYODAY_CC", kind: "credit_card" },
  { name: "Zerodha", institution: "ZERODHA", kind: "broker" },
  { name: "Upstox", institution: "UPSTOX", kind: "broker" },
];

const out = `// GENERATED by scripts/generate-app-data.ts — do not edit by hand.
// Source of truth: supabase/seed/taxonomy_master_from_sure.csv + vendor_to_category_starter.yaml

export interface SeedCategory { name: string; parent: string | null; color: string; icon: string; autoAssignable: boolean; }
export interface SeedRule { priority: number; match: string; category: string; }
export interface SeedAccount { name: string; institution: string; kind: string; }

export const SEED_CATEGORIES: SeedCategory[] = ${JSON.stringify(cats, null, 2)};

export const SEED_RULES: SeedRule[] = ${JSON.stringify(rules.map((r, i) => ({ priority: i + 1, match: r.match, category: r.category })), null, 2)};

export const SEED_ACCOUNTS: SeedAccount[] = ${JSON.stringify(ACCOUNTS, null, 2)};

export const TAXONOMY_NAME_SET: ReadonlySet<string> = new Set(SEED_CATEGORIES.map((c) => c.name));
`;

writeFileSync("src/lib/seed-data.ts", out);
console.log(`seed-data.ts: ${cats.length} categories, ${rules.length} rules, ${ACCOUNTS.length} accounts`);
